# Generated by Django 3.2.25 on 2024-04-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product_model',
            options={'verbose_name': 'Product_model', 'verbose_name_plural': 'Product_models'},
        ),
        migrations.AddField(
            model_name='product_model',
            name='category',
            field=models.CharField(default='NULL', max_length=255),
        ),
        migrations.AddField(
            model_name='product_model',
            name='category_id',
            field=models.IntegerField(default=1),
        ),
    ]
